/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _BOARD_H_
#define _BOARD_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

// DEFINES =====================================================================
// ******** ON BOARD LED        ********
// Pins -- PC05
#define BOARD_LED_GPIO            GPIOC
#define BOARD_LED_PORT            PORTC
#define BOARD_LED_PIN             5U

// ******** UART0 -- DEBUG UART ********
// Pins -- PB17 (tx only)
#define BOARD_UART0_PORT          PORTB
#define BOARD_UART0_TX_PIN        17U
#define BOARD_UART0_RX_PIN        16U

// UART0 PARAMETERS
#define BOARD_DEBUG_UART_BAUDRATE 115200
#define BOARD_DEBUG_UART_TYPE     DEBUG_CONSOLE_DEVICE_TYPE_UART
#define BOARD_DEBUG_UART_BASEADDR UART0
#define BOARD_DEBUG_UART_INSTANCE 0U
#define BOARD_DEBUG_UART_CLKSRC   SYS_CLK
#define BOARD_DEBUG_UART_CLK_FREQ CLOCK_GetCoreSysClkFreq()
#define BOARD_UART_IRQ            UART0_RX_TX_IRQn
#define BOARD_UART_IRQ_HANDLER    UART0_RX_TX_IRQHandler
#define SOPT5_UART0TXSRC_UART_TX  0x00u

// ******** IRDA INTERFACE  ********
// Pins -- PD03
#define BOARD_IRDA_PORT           PORTD
#define BOARD_IRDA_GPIO           GPIOD
#define BOARD_IRDA_CMP1_PIN       3U
#define BOARD_IRDA_IRQ            PORTD_IRQn
#define BOARD_IRDA_IRQ_HANDLER    PORTD_IRQHandler

// Timer for IRDA
#define BOARD_FTM_BASEADDR        FTM3
#define BOARD_FTM_X_CHANNEL       0U
#define BOARD_FTM_Y_CHANNEL       1U
#define BOARD_FTM_PERIOD_HZ       16000
#define BOARD_FTM_PERIOD_TICKS    1875
#define BOARD_FTM_IRQ_HANDLER     FTM3_IRQHandler
#define BOARD_FTM_IRQ_VECTOR      FTM3_IRQn
#define BOARD_FTM_SOURCE_CLOCK    (CLOCK_GetFreq(kCLOCK_BusClk)/4)

// ******** SPI2 -- CHARACTER LCD ********
// Pins -- PB20-22
#define BOARD_SPI2_PORT           PORTB
#define BOARD_SPI2_CS_PIN         20U
#define BOARD_SPI2_CK_PIN         21U
#define BOARD_SPI2_TX_PIN         22U
#define BOARD_SPI2_RX_PIN         23U

// SPI2 PARAMETERS
#define BOARD_SPI2_BASEADDR       SPI2
#define BOARD_SPI2_BAUDRATE       50000U  // 100kHz max by spec
#define BOARD_SPI2_PCS            kDSPI_Pcs0
#define BOARD_SPI2_MASTER_PCS     kDSPI_MasterPcs0
#define BOARD_SPI2_CLKSRC         (CLOCK_GetFreq(DSPI2_CLK_SRC))

// DMA PARAMETERS
#define BOARD_SPI2_DMA_MUX_BASE   DMAMUX
#define BOARD_SPI2_DMA_MUX_SOURCE kDmaRequestMux0SPI2Tx
#define BOARD_SPI2_DMA_RX_SOURCE  kDmaRequestMux0SPI2Rx
#define BOARD_SPI2_DMA_BASE       DMA0

// ******** SDCARD INTERFACE ********
// SDHC base address, clock and card detection pin
#define BOARD_SDHC_BASEADDR       SDHC
#define BOARD_SDHC_CLKSRC         kCLOCK_CoreSysClk
#define BOARD_SDHC_CLK_FREQ       CLOCK_GetFreq(kCLOCK_CoreSysClk)
#define BOARD_SDHC_IRQ            SDHC_IRQn

// ******** SDCARD INSERT PIN ********
// Pins PC08
#define BOARD_SDHC_CD_GPIO_BASE   GPIOC
#define BOARD_SDHC_CD_PORT_BASE   PORTC
#define BOARD_SDHC_CD_GPIO_PIN    8U
#define BOARD_SDHC_CD_PORT_IRQ    PORTC_IRQn
#define BOARD_SDHC_CD_PORT_IRQ_HANDLER PORTC_IRQHandler
#define BOARD_SDHC_CARD_INSERT_CD_LEVEL (0U)

// PROTOTYPES ==================================================================
void BOARD_InitPins(void);
void BOARD_InitDebugConsole(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _HW_CONFIG_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
