/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _HW_CONFIG_H_
#define _HW_CONFIG_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

// DEFINES =====================================================================
// This is for the debug UART interface
#define BOARD_UART0_PORT          PORTB
#define BOARD_UART0_TX_PIN        17U
#define BOARD_UART0_RX_PIN        16U

// LED is on PORTC-05
#define BOARD_LED_GPIO            GPIOC
#define BOARD_LED_PORT            PORTC
#define BOARD_LED_PIN             5U

// UART0 PARAMETERS
#define BOARD_DEBUG_UART_BAUDRATE 115200
#define BOARD_DEBUG_UART_TYPE     DEBUG_CONSOLE_DEVICE_TYPE_UART
#define BOARD_DEBUG_UART_BASEADDR (uint32_t) UART0
#define BOARD_DEBUG_UART_INSTANCE 0U
#define BOARD_DEBUG_UART_CLKSRC   SYS_CLK
#define BOARD_DEBUG_UART_CLK_FREQ CLOCK_GetCoreSysClkFreq()
#define BOARD_UART_IRQ            UART0_RX_TX_IRQn
#define BOARD_UART_IRQ_HANDLER    UART0_RX_TX_IRQHandler
#define SOPT5_UART0TXSRC_UART_TX  0x00u

/* SDHC base address, clock and card detection pin */
#define BOARD_SDHC_BASEADDR       SDHC
#define BOARD_SDHC_CLKSRC         kCLOCK_CoreSysClk
#define BOARD_SDHC_CLK_FREQ       CLOCK_GetFreq(kCLOCK_CoreSysClk)
#define BOARD_SDHC_IRQ            SDHC_IRQn
// SDHC_CD is PORTC-08
#define BOARD_SDHC_CD_GPIO_BASE   GPIOC
#define BOARD_SDHC_CD_PORT_BASE   PORTC
#define BOARD_SDHC_CD_GPIO_PIN    8U
#define BOARD_SDHC_CD_PORT_IRQ    PORTC_IRQn
#define BOARD_SDHC_CD_PORT_IRQ_HANDLER PORTC_IRQHandler
#define BOARD_SDHC_CARD_INSERT_CD_LEVEL (0U)

// PROTOTYPES ==================================================================
void BOARD_InitPins(void);
void BOARD_InitDebugConsole(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _HW_CONFIG_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
