/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

// These are for the onboard SDCARD interface
#define BOARD_SDHC0_PORT     PORTE
#define BOARD_SDHC0_CLK_PIN  2U
#define BOARD_SDHC0_CMD_PIN  3U
#define BOARD_SDHC0_D0_PIN   1U
#define BOARD_SDHC0_D1_PIN   0U
#define BOARD_SDHC0_D2_PIN   4U
#define BOARD_SDHC0_D3_PIN   5U

// LED is on PORTC-05
#define BOARD_LED_GPIO GPIOC
#define BOARD_LED_PORT PORTC
#define BOARD_LED_PIN 5U

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
